
DECLARE @indice INT
DECLARE @id INT
SET @indice = 0


BEGIN TRANSACTION tranx

BEGIN
TRY

	WHILE (@indice < 1000)
	BEGIN
		INSERT INTO B_PRODUCTS 
		VALUES ('Science Kit')
		
		SET @id = cast(@@identity as int)

		INSERT INTO B_PROVIDERS_PRODUCTS
		VALUES (4, @id)

		SET @indice = @indice + 1

commit transaction tranx

	END
	
END TRY
BEGIN CATCH 

	PRINT eRROR_mESSAGE()
	ROLLBACK TRANSACTION tranx

END CATCH
GO


SELECT COUNT(*) FROM B_PRODUCTS
select * from B_PROVIDERS
SELECT * FROM B_PRODUCTS
SELECT * FROM B_PROVIDERS_PRODUCTS

INSERT INTO B_CUSTOMERS
VALUES ('Linda', 'Harley')
INSERT INTO B_CUSTOMERS
VALUES ('Maggie', 'Winslow')
INSERT INTO B_CUSTOMERS
VALUES ('Scott', 'Tiger')
INSERT INTO B_CUSTOMERS
VALUES ('John', 'Anderson')
INSERT INTO B_CUSTOMERS
VALUES ('Abbie', 'Hollister')
INSERT INTO B_CUSTOMERS
VALUES ('Saul', 'Bellow')
INSERT INTO B_CUSTOMERS
VALUES ('Albert', 'Bohr')
INSERT INTO B_CUSTOMERS
VALUES ('Samuel', 'Beckett')
INSERT INTO B_CUSTOMERS
VALUES ('Adrienne', 'Rich')

INSERT INTO B_PROVIDERS 
VALUES ('Dock Systems', '788088077', 'contact@docksystems.com')
INSERT INTO B_PROVIDERS 
VALUES ('Sun Ink.', '067077088', 'contact@sunink.com')
INSERT INTO B_PROVIDERS 
VALUES ('Provider People', '440302302', 'contact@providers.com')
INSERT INTO B_PROVIDERS 
VALUES ('Aloha Technologies', '712004004', 'contact@alohatechs.com')


INSERT INTO B_PRODUCTS 
VALUES ('Old vinyl')
INSERT INTO B_PRODUCTS 
VALUES ('Coat')
INSERT INTO B_PRODUCTS 
VALUES ('RMS Speakers')
INSERT INTO B_PRODUCTS 
VALUES ('Mountain Bike')
INSERT INTO B_PRODUCTS 
VALUES ('Laptop')
INSERT INTO B_PRODUCTS 
VALUES ('Book')

SELECT * FROM B_CUSTOMERS
SELECT * FROM B_PRODUCTS

INSERT INTO B_SALES VALUES (8, 13, '45', '250')
INSERT INTO B_SALES VALUES (8, 9, '1', '185')

INSERT INTO B_SALES VALUES (5, 10, '1', '150')


INSERT INTO B_SALES VALUES (4, 11, '1', '1250')

INSERT INTO B_SALES VALUES (3, 9, '2', '250')
INSERT INTO B_SALES VALUES (3, 12, '1', '450')
INSERT INTO B_SALES VALUES (3, 8, '4', '36')


INSERT INTO B_SALES VALUES (1, 8, '100', '400')
INSERT INTO B_SALES VALUES (1, 12, '1', '475')
INSERT INTO B_SALES VALUES (1, 13, '8', '75')

INSERT INTO B_SALES VALUES (2, 10, '1', '75')
INSERT INTO B_SALES VALUES (1, 13, '6', '55')


INSERT INTO B_PROVIDERS_PRODUCTS VALUES(4, 12)
INSERT INTO B_PROVIDERS_PRODUCTS VALUES(4, 10)
INSERT INTO B_PROVIDERS_PRODUCTS VALUES(4, 11)


INSERT INTO B_PROVIDERS_PRODUCTS VALUES(3, 10)
INSERT INTO B_PROVIDERS_PRODUCTS VALUES(3, 8)
INSERT INTO B_PROVIDERS_PRODUCTS VALUES(3, 12)
INSERT INTO B_PROVIDERS_PRODUCTS VALUES(3, 9)

INSERT INTO B_PROVIDERS_PRODUCTS VALUES(2, 9)
INSERT INTO B_PROVIDERS_PRODUCTS VALUES(2, 11)


INSERT INTO B_PROVIDERS_PRODUCTS VALUES(1, 8)
INSERT INTO B_PROVIDERS_PRODUCTS VALUES(1, 10)
INSERT INTO B_PROVIDERS_PRODUCTS VALUES(1, 13)















