
CREATE TABLE B_PROVIDERS
(
	IdProvider INT IDENTITY(1,1) NOT NULL,
	Name	   VARCHAR(100) NOT NULL,
	Telephone  VARCHAR(20) NOT NULL,
	EMail	   VARCHAR(50) NOT NULL,
	
	CONSTRAINT PK_PROVIDER PRIMARY KEY (IdProvider)
)
GO


CREATE TABLE B_PRODUCTS
(
	IdProduct    INT IDENTITY(1,1) NOT NULL,
	Description  VARCHAR(100) NOT NULL,
	
	CONSTRAINT PK_PRODUCT PRIMARY KEY (IdProduct)
)
GO

CREATE TABLE B_PROVIDERS_PRODUCTS
(
	IdProvider INT NOT NULL,
	IdProduct  INT NOT NULL,
	
	CONSTRAINT PK_PROVIDER_PRODUCT 
		PRIMARY KEY (IdProvider, IdProduct),
	CONSTRAINT FK_PP_PROVIDER
		FOREIGN KEY (IdProvider)
		REFERENCES B_PROVIDERS(IdProvider)
		ON DELETE NO ACTION
		ON UPDATE CASCADE,
	CONSTRAINT FK_PP_PRODUCT
		FOREIGN KEY (IdProduct)
		REFERENCES B_PRODUCTS(IdProduct)
		ON DELETE NO ACTION
		ON UPDATE CASCADE
)
GO


CREATE TABLE B_CUSTOMERS
(
	IdCustomer INT IDENTITY(1,1) NOT NULL,
	FirstName  VARCHAR(20) NOT NULL,
	LastName   VARCHAR(40) NOT NULL,
	FullName   AS FirstName + ' ' + LastName,
	
	CONSTRAINT PK_CUSTOMER PRIMARY KEY (IdCustomer)
)
GO


CREATE TABLE B_SALES
(
	IdSale      INT IDENTITY(1,1) NOT NULL,
	IdCustomer  INT NOT NULL,
	IdProduct   INT NOT NULL,
	Cuantity    INT NOT NULL,
	Price       MONEY NOT NULL,
	
	CONSTRAINT PK_SALE PRIMARY KEY (IdSale),
	CONSTRAINT FK_S_CUSTOMER
		FOREIGN KEY (IdCustomer)
		REFERENCES B_CUSTOMERS(IdCustomer)
		ON DELETE NO ACTION
		ON UPDATE CASCADE,
	CONSTRAINT FK_S_PRODUCTS 
		FOREIGN KEY (IdProduct)
		REFERENCES B_PRODUCTS (IdProduct)
		ON DELETE NO ACTION
		ON UPDATE CASCADE	
)
GO

